nginx_sites:
  dev.mylocal.vn:
    upstream: |-
      server 10.1.110.215:8711;
    server_name: |-
      dev.mylocal.vn
    extra_opt: |-
      client_max_body_size 0;
      include conf.d/cors.conf;
    location_root: |-
      proxy_pass http://ups_dev.mylocal.vn;
      include conf.d/forwarding_proxy.conf;
    forwarding_proxy: "0"
    ssl_enabled: "1"
    ssl_redirect: "1"
    ssl_certificate: "/etc/letsencrypt/live/dev.mylocal.vn/fullchain.pem"
    ssl_certificate_key: "/etc/letsencrypt/live/dev.mylocal.vn/privkey.pem"
    ssl_trusted_certificate: "/etc/letsencrypt/live/dev.mylocal.vn/chain.pem"
